export { default as BoostLearning } from './BoostLearning';
export { default as OurCourses } from './OurCourses';
export { default as BestProfessionals } from './BestProfessionals';
export { default as ChooseFuture } from './ChooseFuture';
export { default as WhyChooseUs } from './WhyChooseUs';
export { default as ResourcesInsights } from './ResourcesInsights';
export { default as Testimonials } from './Testimonials';
export { default as FacilitiesAdvantages } from './FacilitiesAdvantages';
export { default as CoursesCategory } from './CoursesCategory';
